export const product = [
  {
    id: 1,
    product_title: "product_title1",
    img: `${process.env.PUBLIC_URL}/product/product1.jpg`,
    material: "material1",
    category: "category1",
    size: "size1",
    pillow_wear: "pillow_wear1",
    sheet: "sheet1",
    bedding: "bedding1",
    manufacturer: "manufacturer1",
    title: "title1",
    comment: "comment1",
  },
  {
    id: 2,
    product_title: "product_title2",
    img: `${process.env.PUBLIC_URL}/product/product2.jpg`,
    material: "material2",
    category: "category2",
    size: "size2",
    pillow_wear: "pillow_wear2",
    sheet: "sheet2",
    bedding: "bedding2",
    manufacturer: "manufacturer2",
    title: "title2",
    comment: "comment2",
  },
  {
    id: 3,
    product_title: "product_title3",
    img: `${process.env.PUBLIC_URL}/product/product3.jpg`,
    material: "material3",
    category: "category3",
    size: "size3",
    pillow_wear: "pillow_wear3",
    sheet: "sheet3",
    bedding: "bedding3",
    manufacturer: "manufacturer3",
    title: "title3",
    comment: "comment3",
  },
  {
    id: 4,
    product_title: "product_title4",
    img: `${process.env.PUBLIC_URL}/product/product4.jpg`,
    material: "material4",
    category: "category4",
    size: "size4",
    pillow_wear: "pillow_wear4",
    sheet: "sheet4",
    bedding: "bedding4",
    manufacturer: "manufacturer4",
    title: "title4",
    comment: "comment4",
  },
  {
    id: 5,
    product_title: "product_title5",
    img: `${process.env.PUBLIC_URL}/product/product5.jpg`,
    material: "material5",
    category: "category5",
    size: "size5",
    pillow_wear: "pillow_wear5",
    sheet: "sheet5",
    bedding: "bedding5",
    manufacturer: "manufacturer5",
    title: "title5",
    comment: "comment5",
  },
  {
    id: 6,
    product_title: "product_title6",
    img: `${process.env.PUBLIC_URL}/product/bambi.jpg`,
    material: "material6",
    category: "category6",
    size: "size6",
    pillow_wear: "pillow_wear6",
    sheet: "sheet6",
    bedding: "bedding6",
    manufacturer: "manufacturer6",
    title: "title6",
    comment: "comment6",
  },
  {
    id: 7,
    product_title: "product_title7",
    img: `${process.env.PUBLIC_URL}/product/vizantiya.jpg`,
    material: "material7",
    category: "category7",
    size: "size7",
    pillow_wear: "pillow_wear7",
    sheet: "sheet7",
    bedding: "bedding7",
    manufacturer: "manufacturer7",
    title: "title7",
    comment: "comment7",
  },
  {
    id: 8,
    product_title: "product_title8",
    img: `${process.env.PUBLIC_URL}/product/kechki.jpg`,
    material: "material8",
    category: "category8",
    size: "size8",
    pillow_wear: "pillow_wear8",
    sheet: "sheet8",
    bedding: "bedding8",
    manufacturer: "manufacturer8",
    title: "title8",
    comment: "comment8",
  },
  {
    id: 9,
    product_title: "product_title9",
    img: `${process.env.PUBLIC_URL}/product/pat.jpg`,
    material: "material9",
    category: "category9",
    size: "size9",
    pillow_wear: "pillow_wear9",
    sheet: "sheet9",
    bedding: "bedding9",
    manufacturer: "manufacturer9",
    title: "title9",
    comment: "comment9",
  },
  {
    id: 10,
    product_title: "product_title10",
    img: `${process.env.PUBLIC_URL}/product/lavanda.jpg`,
    material: "material10",
    category: "category10",
    size: "size10",
    pillow_wear: "pillow_wear10",
    sheet: "sheet10",
    bedding: "bedding10",
    manufacturer: "manufacturer10",
    title: "title10",
    comment: "comment10",
  },
];
